# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jlcc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='jlcc.proto',
  package='protocols',
  syntax='proto2',
  serialized_options=_b('\n!com.geomodeller.protocols.dc.jobs'),
  serialized_pb=_b('\n\njlcc.proto\x12\tprotocols\"\xa7\x03\n\tJobReport\x12\x0e\n\x06job_id\x18\x01 \x02(\t\x12$\n\x06status\x18\x02 \x02(\x0e\x32\x14.protocols.JobStatus\x12\x11\n\ttimestamp\x18\x03 \x02(\x03\x12\x14\n\x0cnumber_tasks\x18\x04 \x02(\x03\x12\x16\n\x0elatest_task_sn\x18\x05 \x02(\x03\x12\x38\n\x11state_change_type\x18\x06 \x01(\x0e\x32\x1d.protocols.JobStateChangeType\x12\x18\n\x10latest_task_name\x18\x07 \x01(\t\x12\x10\n\x08job_name\x18\x08 \x01(\t\x12\x17\n\x0fjob_description\x18\t \x01(\t\x12\x1c\n\x14percentage_completed\x18\n \x01(\x02\x12\x14\n\x0c\x65lapsed_time\x18\x0b \x01(\x03\x12\x16\n\x0escheduled_time\x18\x0c \x01(\x03\x12\x11\n\tdone_time\x18\r \x01(\x03\x12\x16\n\x0e\x65stimated_time\x18\x0e \x01(\x03\x12\x18\n\tcancelled\x18\x0f \x01(\x08:\x05\x66\x61lse\x12\x13\n\x04\x64one\x18\x10 \x01(\x08:\x05\x66\x61lse\"\x91\x01\n\x07JLCCCmd\x12\'\n\x07\x63ommand\x18\x01 \x02(\x0e\x32\x16.protocols.JLCCCmdEnum\x12\x0e\n\x06job_id\x18\x02 \x02(\t\x12\x15\n\nexec_delay\x18\x03 \x01(\x03:\x01\x30\x12\x15\n\nexec_clock\x18\x04 \x01(\x03:\x01\x30\x12\x10\n\x08priority\x18\x05 \x01(\x05\x12\r\n\x05timer\x18\x06 \x01(\x03*=\n\tJobStatus\x12\x08\n\x04NONE\x10\x00\x12\x0c\n\x08SLEEPING\x10\x01\x12\x0b\n\x07WAITING\x10\x02\x12\x0b\n\x07RUNNING\x10\x04*^\n\x12JobStateChangeType\x12\x10\n\x0c\x41\x42OUT_TO_RUN\x10\x01\x12\t\n\x05\x41WAKE\x10\x02\x12\x08\n\x04\x44ONE\x10\x03\x12\x07\n\x03RUN\x10\x04\x12\r\n\tSCHEDULED\x10\x05\x12\t\n\x05SLEEP\x10\x06*}\n\x0bJLCCCmdEnum\x12\t\n\x05START\x10\n\x12\x08\n\x04KILL\x10\x14\x12\x08\n\x04STOP\x10\x1e\x12\r\n\tHYPNOTIZE\x10(\x12\n\n\x06WAKEUP\x10\x32\x12\x10\n\x0cSET_PRIORITY\x10\x64\x12\x10\n\x0cINC_PRIORITY\x10n\x12\x10\n\x0c\x44\x45\x43_PRIORITY\x10xB#\n!com.geomodeller.protocols.dc.jobs')
)

_JOBSTATUS = _descriptor.EnumDescriptor(
  name='JobStatus',
  full_name='protocols.JobStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SLEEPING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WAITING', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUNNING', index=3, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=599,
  serialized_end=660,
)
_sym_db.RegisterEnumDescriptor(_JOBSTATUS)

JobStatus = enum_type_wrapper.EnumTypeWrapper(_JOBSTATUS)
_JOBSTATECHANGETYPE = _descriptor.EnumDescriptor(
  name='JobStateChangeType',
  full_name='protocols.JobStateChangeType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ABOUT_TO_RUN', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AWAKE', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DONE', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUN', index=3, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCHEDULED', index=4, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SLEEP', index=5, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=662,
  serialized_end=756,
)
_sym_db.RegisterEnumDescriptor(_JOBSTATECHANGETYPE)

JobStateChangeType = enum_type_wrapper.EnumTypeWrapper(_JOBSTATECHANGETYPE)
_JLCCCMDENUM = _descriptor.EnumDescriptor(
  name='JLCCCmdEnum',
  full_name='protocols.JLCCCmdEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='START', index=0, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KILL', index=1, number=20,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=2, number=30,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HYPNOTIZE', index=3, number=40,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WAKEUP', index=4, number=50,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_PRIORITY', index=5, number=100,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INC_PRIORITY', index=6, number=110,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEC_PRIORITY', index=7, number=120,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=758,
  serialized_end=883,
)
_sym_db.RegisterEnumDescriptor(_JLCCCMDENUM)

JLCCCmdEnum = enum_type_wrapper.EnumTypeWrapper(_JLCCCMDENUM)
NONE = 0
SLEEPING = 1
WAITING = 2
RUNNING = 4
ABOUT_TO_RUN = 1
AWAKE = 2
DONE = 3
RUN = 4
SCHEDULED = 5
SLEEP = 6
START = 10
KILL = 20
STOP = 30
HYPNOTIZE = 40
WAKEUP = 50
SET_PRIORITY = 100
INC_PRIORITY = 110
DEC_PRIORITY = 120



_JOBREPORT = _descriptor.Descriptor(
  name='JobReport',
  full_name='protocols.JobReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_id', full_name='protocols.JobReport.job_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='protocols.JobReport.status', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='protocols.JobReport.timestamp', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number_tasks', full_name='protocols.JobReport.number_tasks', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latest_task_sn', full_name='protocols.JobReport.latest_task_sn', index=4,
      number=5, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state_change_type', full_name='protocols.JobReport.state_change_type', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latest_task_name', full_name='protocols.JobReport.latest_task_name', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='job_name', full_name='protocols.JobReport.job_name', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='job_description', full_name='protocols.JobReport.job_description', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='percentage_completed', full_name='protocols.JobReport.percentage_completed', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='elapsed_time', full_name='protocols.JobReport.elapsed_time', index=10,
      number=11, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scheduled_time', full_name='protocols.JobReport.scheduled_time', index=11,
      number=12, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='done_time', full_name='protocols.JobReport.done_time', index=12,
      number=13, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='estimated_time', full_name='protocols.JobReport.estimated_time', index=13,
      number=14, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cancelled', full_name='protocols.JobReport.cancelled', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='done', full_name='protocols.JobReport.done', index=15,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=449,
)


_JLCCCMD = _descriptor.Descriptor(
  name='JLCCCmd',
  full_name='protocols.JLCCCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='protocols.JLCCCmd.command', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=10,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='job_id', full_name='protocols.JLCCCmd.job_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exec_delay', full_name='protocols.JLCCCmd.exec_delay', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exec_clock', full_name='protocols.JLCCCmd.exec_clock', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='priority', full_name='protocols.JLCCCmd.priority', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timer', full_name='protocols.JLCCCmd.timer', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=452,
  serialized_end=597,
)

_JOBREPORT.fields_by_name['status'].enum_type = _JOBSTATUS
_JOBREPORT.fields_by_name['state_change_type'].enum_type = _JOBSTATECHANGETYPE
_JLCCCMD.fields_by_name['command'].enum_type = _JLCCCMDENUM
DESCRIPTOR.message_types_by_name['JobReport'] = _JOBREPORT
DESCRIPTOR.message_types_by_name['JLCCCmd'] = _JLCCCMD
DESCRIPTOR.enum_types_by_name['JobStatus'] = _JOBSTATUS
DESCRIPTOR.enum_types_by_name['JobStateChangeType'] = _JOBSTATECHANGETYPE
DESCRIPTOR.enum_types_by_name['JLCCCmdEnum'] = _JLCCCMDENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JobReport = _reflection.GeneratedProtocolMessageType('JobReport', (_message.Message,), {
  'DESCRIPTOR' : _JOBREPORT,
  '__module__' : 'jlcc_pb2'
  # @@protoc_insertion_point(class_scope:protocols.JobReport)
  })
_sym_db.RegisterMessage(JobReport)

JLCCCmd = _reflection.GeneratedProtocolMessageType('JLCCCmd', (_message.Message,), {
  'DESCRIPTOR' : _JLCCCMD,
  '__module__' : 'jlcc_pb2'
  # @@protoc_insertion_point(class_scope:protocols.JLCCCmd)
  })
_sym_db.RegisterMessage(JLCCCmd)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
